<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE bookstore [
  <!ELEMENT bookstore (book+)>
  <!ELEMENT book (title, author+, price, isbn?, category)>
  <!ELEMENT title (#PCDATA)>
  <!ELEMENT author (#PCDATA)>
  <!ELEMENT price (#PCDATA)>
  <!ELEMENT isbn (#PCDATA)>
  <!ELEMENT category (#PCDATA)>
  <!ATTLIST book
    id ID #REQUIRED
    lang (en|es|fr|de) "en"
    available (yes|no) #REQUIRED>
]>
<bookstore>
  <book id="b001" lang="en" available="yes">
    <title>The Pragmatic Programmer</title>
    <author>Andrew Hunt</author>
    <author>David Thomas</author>
    <price>49.99</price>
    <isbn>978-0135957059</isbn>
    <category>Programming</category>
  </book>
  <book id="b002" lang="en" available="yes">
    <title>Clean Code</title>
    <author>Robert C. Martin</author>
    <price>44.99</price>
    <isbn>978-0132350884</isbn>
    <category>Programming</category>
  </book>
  <book id="b003" lang="es" available="no">
    <title>Design Patterns</title>
    <author>Erich Gamma</author>
    <author>Richard Helm</author>
    <author>Ralph Johnson</author>
    <author>John Vlissides</author>
    <price>54.99</price>
    <isbn>978-0201633610</isbn>
    <category>Software Engineering</category>
  </book>
  <book id="b004" lang="en" available="yes">
    <title>Introduction to Algorithms</title>
    <author>Thomas H. Cormen</author>
    <author>Charles E. Leiserson</author>
    <price>89.99</price>
    <category>Computer Science</category>
  </book>
</bookstore>
